---
title: Falling stars
hero_image: images/banner.png
description: Maak een platform-achtige game en voeg je eigen levels, power-ups en personages toe.
theme: orange
listed: true
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: "2018-04-23"
steps:
  - 
    title: Inleiding
  - 
    title: De voorbereidingen
  - 
    title: Het spel verliezen
  - 
    title: Power-ups
  - 
    title: Super power-ups!
  - 
    title: "Uitdaging: wees creatief!"
    challenge: true
  - 
    title: Een wedstrijd element toevoegen
  - 
    title: Level 2
  - 
    title: Bewegende platforms
  - 
    title: Wat komt er nu?
