---
title: Fallende Sterne
hero_image: images/banner.png
description: Erstelle ein Spiel im Plattform-Stil und füge deine eigenen Levels, Fähigkeiten und Charaktere hinzu.
theme: orange
listed: true
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: '2018-04-23'
steps:
  - 
    title: Einleitung
  - 
    title: Vorbereitungen
  - 
    title: Das Spiel verlieren
    completion:
      - engaged
  - 
    title: Power-Up
  - 
    title: Super Power-Ups!
  - 
    title: 'Herausforderung: Werde kreativ!'
    challenge: true
  - 
    title: Die Schwierigkeit erhöhen
  - 
    title: Level 2
  - 
    title: Bewegliche Plattformen
    completion:
      - internal
  - 
    title: Wie geht es weiter?
