---
title: Estrellas fugaces
hero_image: images/banner.png
description: Crea un juego de plataforma y agrega tus propios niveles, poderes y personajes.
theme: orange
listed: true
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: juegos
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: "2018-04-23"
steps:
  - 
    title: Introducción
  - 
    title: Preparando todo
  - 
    title: Perdiendo el juego
  - 
    title: Potenciadores
  - 
    title: '¡Superpotenciadores!'
  - 
    title: "Desafío: ¡sé creativo!"
    challenge: true
  - 
    title: Agregando un poco de competencia
  - 
    title: Nivel 2
  - 
    title: Plataformas móviles
  - 
    title: '¿Qué sigue?'
