---
title: Falling stars
hero_image: images/banner.png
description: Make a platform-style game and add your own levels, powers, and characters.
theme: orange
listed: true
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ألعاب
technologies: scratch
site_areas: كودر دوجو
software: scratch
version: 4.0.0
last_tested: "2018-04-23"
steps:
  - 
    title: المقدمة
  - 
    title: ضبط الأمور
  - 
    title: خسارة اللعبة
  - 
    title: Power-ups
  - 
    title: Super power-ups!
  - 
    title: "تحدي: كن مبدعا!"
    challenge: true
  - 
    title: إضافة بعض المنافسة
  - 
    title: المستوى ٢
  - 
    title: منصات متحركة
  - 
    title: ما التالي؟
