---
title: Stelle cadenti
hero_image: images/banner.png
description: Crea un gioco in stile piattaforma e aggiungi i tuoi livelli, poteri e personaggi.
theme: arancio
listed: true
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: giochi
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: '2018-04-23'
steps:
  - 
    title: Introduzione
  - 
    title: Impostare il tutto
  - 
    title: Perdere al gioco
    completion:
      - engaged
  - 
    title: Potenziamenti
  - 
    title: Super potenziamenti!
  - 
    title: 'Sfida: diventa creativo!'
    challenge: true
  - 
    title: Aggiungiamo un po' di competizione
  - 
    title: Livello 2
  - 
    title: Piattaforme mobili
    completion:
      - internal
  - 
    title: E adesso?
